language: java
jdk:
  - openjdk12
notifications:
  email: false
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - openssl aes-256-cbc -K $encrypted_d9f9cea8be1e_key -iv $encrypted_d9f9cea8be1e_iv
    -in deploy/marmoush.com.gpg.enc -out deploy/marmoush.com.gpg -d
  - gpg --import deploy/marmoush.com.gpg

after_success:
  - bash <(curl -s https://codecov.io/bash)
install: mvn install
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml -P travis_deployment
  on:
    branch: master
    tags: true
branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/
env:
  global:
    - secure: Q03gRquDHtOqEqZyOKS8G5QhX7ktDvJyQlXmb07k+wfLY8K2FtACU9KIvbLe0AHEfmh8HKrTMWRFCuRQq/OryoRMm9BqbcH7RM8CUGAxh7kG9ZVfuHmo+cmJCuso92YGI7p1sh7uVtcDe21rrxKCbzn4Q5IZLyD8yJBTEEO1mIAh7ObDN+w8ulJpiCD4sQ8TWZoPS9S/0fFpjg6g5BakeyL9/O3FgrF337DKfZZSczGalUggw07Nu6KCU7r9DhzBtbLmra+M452pDSIgbY1+XKwmXvTvEcK+eLZVDrl3l1XGmKuD8uEzPsOkipGa7gFLbdOI0h3Yzde7z84M7UVPtWmMzeHo6m+3CZ8+vbFOimd397j24O4ZZQOHitpe8JvKDDxX6zNbOkncN9Vnpw/MnIjDsGGFrMsoC2bLVesLQYv4KYvsca1kmc/TM5gcfyB2vKF1eC6i+FSkOjE5ZpttrCdKPPWlA44kE5FmOTQNcroFTSONMtqnONd0DOpma029dvEh2A4Eq2rm189LvZiUrp0/xQg2eg/ZIB5KOzzx7+6JMgyq6vEUXfEPSSZhgCVgurKt+gplO+Hn595gDSVWAZ62tjGhzr27dxcz3Qv0h4bWP5tt6lCxrhKypd/w6eg5zbXGNVelNnXrGmpWFSslqwJpG0q5bPFx1IMz0svnU6I=
    - secure: xOMr1x+dHk1naSuOL4ElGOlsjuMxfnnx59qDCHxPmGyi9ufnIMqn/lqw6aGEw1YtuMyaojM5TrnJS/dziAlqyh/PfQwDOFk9xKySGu1LHoGMpjGaeT8h9axjqgW8MEQ1I6TojzossuFPXdLX12ndlDn7tyM5pOOSsVxmpT5NuUtQ6XzmLNhmzQ1EAwT8ZBp4CeWf8tg4OZ+2M1RYX5V6W2J39zp6kZOLRlyPF718cD77r+Il22D/6M4OJkvHkdxH0pOZGL8/JQ3lxM3mRcj+088w5Y0RCYlt0J7+5i8nkQCDBaZi6PjpNV3tlZz4AvoXYW4aFKD+9rq9yErD8l0IrM6exy+usTRPiT/xSYD+aIULOc3wQnzp5k+IYQFD//w/IKy0im40zAxpbwW6zLLmPhlAMzgTxIEXsc7ibVqmXiWwDfZcSOF9JONlGqUOW2kAm5wgthNvT9u+okOImTC3ITC1BK2OeajclYRassqskYg94IhE7pxT49MTPQx1RqZ133NhbL2QEEHoO/nv/nynapbE7K/oZKfYnaeGS8uwfjqTYfRYoLnKAWy0LRfZ1O/H+LMCX1mXjNCMEw9m7olSEDN22+J9ZSr1kd8m4rbAlU/JM1Ifw8ir2jA7MGTLKkbrdQdGb7U9JfUc+Mi9Q83k3+s2pj+nZj1tz04erQAdVo4=
    - secure: uhNGbYUUar9589r6R4U9Y9CuyhMIwvv1/eAdd/sbNkjq+0q+N0EQrDKVraUArn7pW92EAlsHihS7/aqxKchgwvJHBczoORzluylgLF3oFVYlzOJVUr5n1bRoTRdMptFp3/wKEvCGoOsaNhf0dcJhLsj2Z97op9Lo0+U0zoKLq+h+IoFO54IWQm5oy8H0fqFA548cqCCzpQmJQ76TyWd7XyUfBIZim4Of4XVOYjQEFEVHzSIePOnHuCmX9Y7PNbs33lTmcaywJiCWYZoHHCZlBqRaZhRGiPzRpyab1MpQkapmpDLPDlT88Tw7b6VOmVc97Ikfe85esU96F8PGtxSbN1/0CtjW0DbbVkk7HiHa/MpeyX4UMOWspgEmxJ9xdbCM7iGh4FA++5zO5p2llE1l9oo/3OtG0SVimFUtSXA9YHwnYgddeU1VI9W6064DEUdzD8IefZse05Q4JCp1S1tt4J0sjJBC+ypwcYX4bc03vzOM8tdgTwh8Ig+WB3whEvK6DGbxktrVQGQ60XZrlfJ6CEn4Cs/vjPP/prDU+oeXngeoiqgQQZcjQbmA6TNEiNEmNz++7ao4zeZCRtppJLgOEPiR9C1rta10vDvAWSeAnbTWmOAWTsd1laKfcWWW6ruQzZoW3deWjnBCDyab/ePfwHOPW+ZCR0FtZhAHGsksAfQ=
    - secure: S9Lw41j4VdhjN6ukrquZsu4pGu3+bq2GTz4OgPu934TlLUrMHODd2DIFhjiRm7jLj5uZ8ZlrWnJR/hP0lzU4eCz4G7TkM/UTKxzvggA86fBvoaYgextkpYHb2lwtoc4EJkWPRm+rkuhg0UiyeZx9n2TWOS4bGIV1M68CeOEhNwPQZ7eJ4Zs+iSbWoefJMG1bhREOjAmRW4Pzhdfmf65PnZnhTtZbH7KR5H4cONS1QbGiqZgz4laEFoC4AMFVm4DT4wdJGAaoVs6mk8XHFeaw3ZHao2KSra7G2v8CsDNgD//OswczfLDPYd2rTBrGL5BBW3Mv+U4LiC+ZCMKc80HUTK/YGLbaImlnIXe/mGWadZdw7JEWqEWOIsAi0x0dcoW4slY1pJoRfsEdzVl8A+6CPI0rmslV1GatQnNMLGmUuHSlqJRfjbZMxS/WK8dtecYuofxA+3Mf+F9q+w/BnC3fSRc0+XorNKntSgpa1qwZg+ScQKx6BS4vJHzPSuHG6sPB/tvi+CVC6W4Owam3NkC+zAq0oJgC/cNXIo04Z3UM1KggjP3haBbFvtLsoswfqCLIQjQ0TtbNeyD6+GZsXj2lZxKrOeY+60hYX2IxNf2eLYpBlJkrdsRZOFnlD0FYyHOE8HMD9ibeelXhipk2mS/xrLzVeZ5aHbUvN1T2w752v8Q=
